// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// five_uneven_peak_trap
tFitness five_uneven_peak_trap(const double *x, const int &dim);
RcppExport SEXP nmmso_five_uneven_peak_trap(SEXP *xSEXP, SEXP &dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const double >::type *x(*xSEXP);
    Rcpp::traits::input_parameter< const int >::type &dim(&dimSEXP);
    __result = Rcpp::wrap(five_uneven_peak_trap(*x, &dim));
    return __result;
END_RCPP
}
