// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// equal_maxima
tFitness equal_maxima(const double *x, const int &dim);
RcppExport SEXP nmmso_equal_maxima(SEXP *xSEXP, SEXP &dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const double >::type *x(*xSEXP);
    Rcpp::traits::input_parameter< const int >::type &dim(&dimSEXP);
    __result = Rcpp::wrap(equal_maxima(*x, &dim));
    return __result;
END_RCPP
}
